name: front
description: "A new Flutter project."

publish_to: 'none'  # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  sensors_plus: ^6.1.1
  proximity_sensor: ^1.2.0
  camera: ^0.11.1
  http: ^1.3.0
  async: ^2.12.0  # Alinhar para versão 2.12.0, compatível com flutter_test
  material_color_utilities: ^0.11.1  # Use 0.11.1 to avoid conflict with flutter_test
  cupertino_icons: ^1.0.8
  audioplayers: ^5.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  fake_async: ^1.3.2  # Alinhar para versão 1.3.2, compatível com flutter_test
  leak_tracker: ^10.0.8  # Use 10.0.8 to match the version used by flutter_test
  vm_service: ^14.3.1  # Pin this version to match flutter_test

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  # Adicione esta seção para incluir o arquivo de som
  assets:
    - assets/alarm_sound.mp3